### ISSUE TITLE
Favicon?

### ISSUE THREAD

**Issue by cbp2170** [meow56/Kixley#3]
What happened to the K thing we made? Also, do we actually want to use that or should we just use the sword?

**Comment by bowTiesAreCool** [comment]
The K, for comparison:
![kixley_logo-just_k png](https://user-images.githubusercontent.com/16725809/41360452-6e0c0a6c-6ef2-11e8-94b7-4b352d583092.jpeg)

**Comment by bowTiesAreCool** [comment]
Should probably also put the sword here for easier comparison:
![screenshot 2018-06-13 at 10 16 06](https://user-images.githubusercontent.com/16725809/41360626-d564a02a-6ef2-11e8-9d2e-b74e85440b43.png)
The extra black at the bottom is because this is a screenshot because GitHub doesn't support .ico files. Also I'm fairly certain the black would we transparent here. Not in the first one, though.

**Comment by bowTiesAreCool** [comment]
I'm voting for the K but the sword is also good.

**Comment by meow56** [comment]
Meh, I dunno. The K makes sense but if we do choose it we better make something better than just "K in a Google Doc".

**Comment by meow56** [comment]
![kixley k](https://user-images.githubusercontent.com/16784333/42548411-80169c2c-848c-11e8-8df5-6e0a77bd4f6a.png)

Maybe something like this?

**Comment by cbp2170** [comment]
Maybe, but I did like the old coloration. I'll work on that.

**Comment by meow56** [comment]
![kixley k](https://user-images.githubusercontent.com/16784333/43050652-7c699ada-8dd2-11e8-830d-56f7802f79b3.png)
Like that, then.

**Comment by cbp2170** [comment]
Yeah

**Comment by meow56** [comment]
Done, I guess
